# 회원 정보 USER_INFO
# 상품 판매 정보 ONLINE_SALE

-- 2021 년에 가입한 회원 중 상품을 구매한 회원수, 상품을 구해한 회원의 비율을 년,월 별로 조회

# SELECT  YEAR(SALE.SALES_DATE) AS YEAR,
#         MONTH(SALE.SALES_DATE) AS MONTH,
        
#         COUNT(DISTINCT SALE.USER_ID) AS PUCHASED_USERS,
        
#         COUNT(DISTINCT SALE.USER_ID) /(SELECT COUNT(DISTINCT INFO.USER_ID)
#          FROM USER_INFO  AS INFO
#          WHERE YEAR(INFO.JOINED) = '2021'
#         ) AS PUCHASED_RATIO

# FROM USER_INFO AS INFO JOIN ONLINE_SALE AS SALE ON INFO.USER_ID = SALE.USER_ID
# WHERE YEAR(INFO.JOINED) = '2021'
# GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE)
# ORDER BY YEAR, MONTH;



SELECT  YEAR(SALE.SALES_DATE) AS YEAR,
        MONTH(SALE.SALES_DATE) AS MONTH,
        COUNT(DISTINCT SALE.USER_ID) AS PUCHASED_USERS,
        
        ROUND(COUNT(DISTINCT SALE.USER_ID) /(SELECT COUNT(DISTINCT INFO.USER_ID)
                                             FROM USER_INFO AS INFO
                                             WHERE YEAR(INFO.JOINED) = '2021') ,1)
         AS PUCHASED_RATIO
        
FROM USER_INFO AS INFO JOIN ONLINE_SALE AS SALE ON INFO.USER_ID = SALE.USER_ID
WHERE SALE.USER_ID IN (  SELECT USER_ID
                         FROM USER_INFO
                         WHERE YEAR(INFO.JOINED) = '2021'
                      )
GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE)
ORDER BY YEAR, MONTH;
