# SELECT COUNT(*)-COUNT(LENGTH) AS FISH_COUNT
# FROM FISH_INFO;

# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO
# WHERE LENGTH IS NULL;

SELECT SUM(IF(LENGTH IS NULL, 1,0)) AS FISH_COUNT
FROM FISH_INFO;