-- 0시부터 23시까지 각 시간대별 입양 건수 조회
-- 시간 순으로 asc;

# SELECT  HOUR(DATETIME) AS HOUR,
#         COUNT(ANIMAL_ID) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR
# ORDER BY HOUR ASC;

SET @HOUR = -1;
SELECT  (@HOUR := @HOUR +1) AS HOUR,
        (SELECT COUNT(HOUR(DATETIME))
         FROM ANIMAL_OUTS
         WHERE HOUR(DATETIME) = @HOUR) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23;

