# ANIMAL_INS 보호소 들어온 동물의 정보
# ANIMAL_OUTS 입양 보낸 동물의 정보

-- 입양을 못간 동물 중, 가장 오래 보호소에 있던 동물 3마리
-- 보호 시작일 기준으로 ASC;

# SELECT INS.NAME, INS.DATETIME
# FROM ANIMAL_INS AS INS LEFT JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
# WHERE OUTS.ANIMAL_ID IS NULL
# ORDER BY DATETIME
# LIMIT 3;


SELECT NAME, DATETIME
from ANIMAL_INS
WHERE ANIMAL_ID not in (
    select ANIMAL_ID
    from ANIMAL_OUTS
) 
order by DATETIME
limit 3