-- 123
-- 456
-- 789
-- 10 11 12

SELECT CONCAT(QUARTER, 'Q') QUARTER, COUNT(*) ECOLI_COUNT
FROM (
    SELECT ID,
        CASE
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3'
            ELSE '4'
        END QUARTER
    FROM ECOLI_DATA
    ) QUARTER_TABLE
GROUP BY QUARTER
ORDER BY QUARTER