-- 코드를 입력하세요
SELECT
    CASE
        WHEN PRICE BETWEEN 0 AND 9999 THEN 0
        ELSE TRUNCATE(PRICE, -4)
    END AS PRICE_GROUP,
    COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC;
