# 식품의 정보         FOOD_PRODUCT
# 식품의 주문 정보     FOOD_ORDER

-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회
-- 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬

SELECT  FOOD_PRODUCT.PRODUCT_ID, 
        FOOD_PRODUCT.PRODUCT_NAME,
        SUM(FOOD_ORDER.AMOUNT) * FOOD_PRODUCT.PRICE AS TOTAL_SALES

FROM FOOD_PRODUCT JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE FOOD_ORDER.PRODUCE_DATE LIKE '2022-05-%'
GROUP BY FOOD_PRODUCT.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;