SELECT FI.ID, F.FISH_NAME, F.LENGTH
FROM(
    SELECT FNI.FISH_TYPE, FNI.FISH_NAME, MAX(FI.LENGTH) LENGTH
    FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
    GROUP BY FNI.FISH_NAME, FNI.FISH_TYPE
    ) F LEFT JOIN FISH_INFO FI ON F.FISH_TYPE = FI.FISH_TYPE AND F.LENGTH = FI.LENGTH
ORDER BY FI.ID;