SELECT MAX_SCORE.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM(
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO 
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
    ) MAX_SCORE, HR_EMPLOYEES HE
WHERE HE.EMP_NO = MAX_SCORE.EMP_NO;

