SELECT SUM(SCORE) SCORE, HE.EMP_NO EMP_NO, HE.EMP_NAME EMP_NAME, HE.POSITION POSITION, HE.EMAIL EMAIL
FROM HR_EMPLOYEES HE JOIN HR_GRADE HD ON HE.EMP_NO = HD.EMP_NO
WHERE YEAR = '2022'
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1